spring.application.name=pawfolio-backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.wkgmxmgdzaoctqjclzkz&password=Jjong_park28
# remove question mark onwards for env
spring.datasource.username=kyraikkonen
spring.datasource.password=Jjong_park28

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect